Install package GetOldTweets3

In [9]:
import GetOldTweets3 as got
from datetime import date, timedelta
from sqlite3 import connect
import pandas as pd
import time
import os

In [2]:
df_Cities=pd.read_excel('uscities.xlsx')

In [6]:
df_Cities=df_Cities[df_Cities['population']>75000]
print(df_Cities.shape[0])
len(df_Cities['state_id'].unique())

631

52

In [1]:
L=['covid','covid-19' , 'covid19' ,'pandemic','reopen','shutdownorder','lockdownorder','stayathomeorder']

searchKeywords ='%20OR%20'.join(L[:6])
print(searchKeywords)
startDate = date(2020, 3, 1)+timedelta(days=0)
endDate =startDate+timedelta(days=76)
MaxTweets=10000
Within="10mi"
Set_Emoji="unicode"
Sleep_time=16*60
print(startDate)
print(endDate)

covid%20OR%20covid-19%20OR%20covid19%20OR%20pandemic%20OR%20reopen%20OR%20shutdownorder

NameError: name 'date' is not defined

In [18]:
len ([state for state in df_Cities['state_id'].unique() if not os.path.exists(state+'Tweet.xlsx')])

16

In [19]:
# j=6, 9, 18, 19, 20, 29
j=0
#for state in df_Cities['state_id'].unique():
for state in [state for state in df_Cities['state_id'].unique() if not os.path.exists(state+'Tweet.xlsx')]:
    
    print(20*'--','j=',j,20*'--')

    df=pd.DataFrame()
    writer = pd.ExcelWriter(state+'Tweet.xlsx')

    for i in df_Cities[df_Cities['state_id']==state].index:
        print(state,'\t', df.shape[0],'\t', df_Cities.loc[i,'city'])


        for d in range(0,76,5):


            startDate = date(2020, 3, 1)+timedelta(days=d)
            endDate =startDate+timedelta(days=5)
            print(startDate)
            #print(endDate)
            city=str(df_Cities.loc[i,'lat'])+','+str(df_Cities.loc[i,'lng'])



            tweetCriteria = got.manager.TweetCriteria().setQuerySearch(searchKeywords)\
                                                           .setSince(str(startDate))\
                                                           .setUntil(str(endDate))\
                                                           .setNear(city)\
                                                           .setMaxTweets(MaxTweets)\
                                                           .setWithin(Within)\
                                                           .setEmoji(Set_Emoji)
            k=0
            while k<5:
                #print('\t','try=',k)
                try: 
                    for tweet in got.manager.TweetManager.getTweets(tweetCriteria):
                        x={'pri_id': tweet.id,
                        'text': tweet.text,
                        'CreateDateTime': tweet.date.strftime("%Y-%m-%d %H:%M"),
                        'CreateDate': tweet.date.strftime("%Y-%m-%d"),
                        'geo': tweet.geo,
                        'to_p': tweet.to,
                        'permalink': tweet.permalink,
                        'username':tweet.username,
                        'retweets': tweet.retweets,
                        'favorites':tweet.favorites,
                        'hashtags' :tweet.hashtags,
                        'mentions' :tweet.mentions,
                        'lat': df_Cities.loc[i,'lat'],
                        'lng': df_Cities.loc[i,'lng'],
                        'city': df_Cities.loc[i,'city'],
                        'state_id': df_Cities.loc[i,'state_id'],
                        'state_name': df_Cities.loc[i,'state_name'],
                        'Loc_id':df_Cities.loc[i,'id']}

                        df=df.append(x,ignore_index=True)
                    k=5
                except:
                    print('Error','\t','try=',k,'  \t', startDate)
                    k+=1
                    time.sleep(Sleep_time)
                #print(x)

    df.to_excel(writer,'Sheet1')
    writer.save()
    j+=1

---------------------------------------- j= 0 ----------------------------------------
DE 	 0 	 Dover
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 1 ----------------------------------------
WV 	 0 	 Charleston
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
WV 	 928 	 Wheeling
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
WV 	 1145 	 Huntington
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 2 ----------------------------------------
HI 	 0 	 Honolulu
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
An error occured during an HTTP request: HTTP Error 503: Service Temporarily Unavailable
Try to open in browser: https://twitter.com/search?q=covid%2520OR%2520covid-19%2520OR%2520covid19%2520OR%2520pandemic%2520OR%2520reopen%2520OR%2520shutdownorder%20near%3A%2221.3294%2C-157.846%22%20within%3A10mi%20since%3A2020-04-15%20until%3A2020-04-20&src=typd
Error 	 try= 0   	 2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 3 ----------------------------------------
WY 	 0 	 Cheyenne
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 4 ----------------------------------------
NH 	 0 	 Portsmouth
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
NH 	 645 	 Dover
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
NH 	 964 	 Manchester
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
NH 	 1676 	 Nashua
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 5 ----------------------------------------
AK 	 0 	 Anchorage
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 6 ----------------------------------------
ND 	 0 	 Bismarck
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
ND 	 292 	 Fargo
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 7 ----------------------------------------
NE 	 0 	 Omaha
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=covid%2520OR%2520covid-19%2520OR%2520covid19%2520OR%2520pandemic%2520OR%2520reopen%2520OR%2520shutdownorder%20near%3A%2241.2628%2C-96.0498%22%20within%3A10mi%20since%3A2020-05-15%20until%3A2020-05-20&src=typd
Error 	 try= 0   	 2020-05-15
NE 	 3414 	 Lincoln
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 8 ----------------------------------------
AR 	 0 	 Fort Smith
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
AR 	 257 	 Little Rock
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
AR 	 4855 	 Fayetteville
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
AR 	 5324 	 Springdale
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 9 ----------------------------------------
VT 	 0 	 Burlington
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 10 ----------------------------------------
ID 	 0 	 Meridian
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=covid%2520OR%2520covid-19%2520OR%2520covid19%2520OR%2520pandemic%2520OR%2520reopen%2520OR%2520shutdownorder%20near%3A%2243.6112%2C-116.3968%22%20within%3A10mi%20since%3A2020-04-25%20until%3A2020-04-30&src=typd
Error 	 try= 0   	 2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
ID 	 1682 	 Idaho Falls
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
ID 	 1774 	 Nampa
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
ID 	 2304 	 Coeur d'Alene
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
ID 	 2549 	 Boise
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 11 ----------------------------------------
ME 	 0 	 Portland
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 12 ----------------------------------------
MT 	 0 	 Billings
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
MT 	 211 	 Missoula
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 13 ----------------------------------------
MS 	 0 	 Gulfport
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
MS 	 740 	 Hattiesburg
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10

2020-05-15
MS 	 1005 	 Jackson
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 14 ----------------------------------------
KY 	 0 	 Louisville
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=covid%2520OR%2520covid-19%2520OR%2520covid19%2520OR%2520pandemic%2520OR%2520reopen%2520OR%2520shutdownorder%20near%3A%2238.1663%2C-85.6485%22%20within%3A10mi%20since%3A2020-03-26%20until%3A2020-03-31&src=typd
Error 	 try= 0   	 2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
KY 	 4620 	 Lexington
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
KY 	 5540 	 Elizabethtown
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
KY 	 9601 	 Bowling Green
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
---------------------------------------- j= 15 ----------------------------------------
SD 	 0 	 Rapid City
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15
SD 	 245 	 Sioux Falls
2020-03-01
2020-03-06
2020-03-11
2020-03-16
2020-03-21
2020-03-26
2020-03-31
2020-04-05
2020-04-10
2020-04-15
2020-04-20
2020-04-25
2020-04-30
2020-05-05
2020-05-10
2020-05-15

In [ ]:
print(j)

In [ ]:
j=0
for state in df_Cities['state_id'].unique()[j:1]:
    print(20*'---')
    
    df=pd.DataFrame()
    writer = pd.ExcelWriter(state+'Tweet.xlsx')
    
    for i in df_Cities[df_Cities['state_id']==state].index:
            
        
        print(state,'\t', df.shape[0],'\t', df_Cities.loc[i,'city'])

        
        city=str(df_Cities.loc[i,'lat'])+' ,'+str(df_Cities.loc[i,'lng'])


        tweetCriteria = got.manager.TweetCriteria().setQuerySearch(searchKeywords)\
                                                       .setSince(str(startDate))\
                                                       .setUntil(str(endDate))\
                                                       .setNear(city)\
                                                       .setMaxTweets(MaxTweets)\
                                                       .setWithin(Within)\
                                                       .setEmoji(Set_Emoji)

                



        k=0
        while k<5:
            #print('\t','try=',k)
            try: 
                for tweet in got.manager.TweetManager.getTweets(tweetCriteria):
                    x={'pri_id': tweet.id,
                    'text': tweet.text,
                    'CreateDateTime': tweet.date.strftime("%Y-%m-%d %H:%M"),
                    'CreateDate': tweet.date.strftime("%Y-%m-%d"),
                    'geo': tweet.geo,
                    'to_p': tweet.to,
                    'permalink': tweet.permalink,
                    'username':tweet.username,
                    'retweets': tweet.retweets,
                    'favorites':tweet.favorites,
                    'hashtags' :tweet.hashtags,
                    'mentions' :tweet.mentions,
                    'lat': df_Cities.loc[i,'lat'],
                    'lng': df_Cities.loc[i,'lng'],
                    'city': df_Cities.loc[i,'city'],
                    'state_id': df_Cities.loc[i,'state_id'],
                    'state_name': df_Cities.loc[i,'state_name'],
                    'Loc_id':df_Cities.loc[i,'id']}

                    df=df.append(x,ignore_index=True)
                k=5
            except:
                print('Error','\t','try=',k)
                k+=1
                time.sleep(240)

        time.sleep( Sleep_time )
            
    df.to_excel(writer,'Sheet1')
    writer.save()
    j+=1

In [ ]:
[x for x in range(0,76,5)]